# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInfo',
        ),
        migrations.AlterModelOptions(
            name='bookorder',
            options={'verbose_name': '学院教材征订表', 'verbose_name_plural': '学院教材征订表'},
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='Amount',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='CourseID',
            field=models.CharField(max_length=10, verbose_name='课程号'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='Major',
            field=models.CharField(max_length=30, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='Term',
            field=models.CharField(max_length=30, verbose_name='学期'),
        ),
        migrations.AlterModelTable(
            name='bookorder',
            table='colodform',
        ),
    ]
