# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20170625_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('Number', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='operations.BookOrder', verbose_name='编号')),
                ('Bookname', models.CharField(max_length=30, verbose_name='书名')),
                ('Press', models.CharField(max_length=30, verbose_name='出版社')),
                ('Author', models.CharField(max_length=30, verbose_name='作者')),
                ('Edition', models.CharField(max_length=10, verbose_name='版次')),
                ('Price', models.FloatField(max_length=30, verbose_name='单价')),
            ],
            options={
                'verbose_name': '书籍信息表',
                'verbose_name_plural': '书籍信息表',
                'db_table': 'bookinfor',
            },
        ),
    ]
