# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_bookinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
