# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.UserInfo', verbose_name='管理员id')),
                ('Aname', models.CharField(max_length=30, verbose_name='姓名')),
                ('Asex', models.CharField(max_length=6, verbose_name='性别')),
                ('Aage', models.CharField(max_length=4, verbose_name='年龄')),
                ('Aphone', models.CharField(max_length=20, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
                'db_table': 'managerform',
            },
        ),
        migrations.CreateModel(
            name='ColRspPsInfo',
            fields=[
                ('SecreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.UserInfo', verbose_name='学院负责人id')),
                ('Sename', models.CharField(max_length=30, verbose_name='姓名')),
                ('Sesex', models.CharField(max_length=5, verbose_name='性别')),
                ('Seage', models.CharField(max_length=4, verbose_name='年龄')),
                ('Sephone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('Semajor', models.CharField(max_length=30, verbose_name='专业')),
            ],
            options={
                'verbose_name': '学院负责人信息表',
                'verbose_name_plural': '学院负责人信息表',
                'db_table': 'colrepform',
            },
        ),
        migrations.CreateModel(
            name='StudenfInfo',
            fields=[
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.UserInfo', verbose_name='学生id')),
                ('Sname', models.CharField(max_length=30, verbose_name='姓名')),
                ('Ssex', models.CharField(max_length=5, verbose_name='性别')),
                ('Sage', models.CharField(max_length=4, verbose_name='年龄')),
                ('Sphone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('Smajor', models.CharField(max_length=30, verbose_name='专业')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
                'db_table': 'stuform',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.UserInfo', verbose_name='教师id')),
                ('Tname', models.CharField(max_length=30, verbose_name='姓名')),
                ('Tsex', models.CharField(max_length=5, verbose_name='性别')),
                ('Tage', models.CharField(max_length=4, verbose_name='年龄')),
                ('Tphone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('Tmajor', models.CharField(max_length=30, verbose_name='专业')),
            ],
            options={
                'verbose_name': '教师信息表',
                'verbose_name_plural': '教师信息表',
                'db_table': 'tchform',
            },
        ),
    ]
