# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admininfo_colrsppsinfo_studenfinfo_teacherinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='用户名'),
        ),
    ]
