# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170625_0046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudenfInfo',
            new_name='StudentInfo',
        ),
    ]
